title: Bathsheba Darko
description: A portfolio showcasing my data science projects and experience.
url: "https://shebadarko.github.io"
#theme: minimal-mistakes-jekyll
#remote_theme  : "mmistakes/minimal-mistakes"

# Build settings
# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


plugins:
  - jekyll-feed

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


