title: Bathsheba Darko
description: A portfolio showcasing my data science projects and experience.
url: "https://shebadarko.github.io"
#theme: minimal-mistakes-jekyll
remote_theme  : "mmistakes/minimal-mistakes"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->

plugins:
  - jekyll-feed

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Feed settings
feed:
  path: feed.xml
